catalogs:
  default:
    '@docusaurus/core': ^3.9.2
    '@docusaurus/logger': ^3.9.2
    '@docusaurus/plugin-content-docs': ^3.9.2
    '@docusaurus/preset-classic': ^3.9.2
    '@docusaurus/theme-mermaid': ^3.9.2
    '@docusaurus/tsconfig': ^3.9.2
    '@docusaurus/types': ^3.9.2
    '@mdx-js/react': ^3.1.1
    '@types/mdast': ^4.0.4
    '@types/unist': ^3.0.3
    clsx: ^2.0.0
    knip: ^5.79.0
    mdast-util-from-markdown: ^2.0.2
    prism-react-renderer: ^2.3.0
    react: ^19.2.4
    react-dom: ^19.2.3
    remark: ^15.0.1
    typescript: ~5.9.3
    unified: ^11.0.5
    unist-util-visit: ^5.0.0

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - core-js
  - core-js-pure
