import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebarsDev: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  dev: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsDev;
