name: Update CI Develop

on:
  workflow_dispatch: {}
###  Next proposed step is to automate the update on push.
#  push:
#    branches:
#      - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_USER_NAME: "${{ github.actor }}"
  GIT_USER_EMAIL: "${{ github.actor }}@users.noreply.github.com"
  SCRIPTS_PATH: "${{ github.workspace }}/sh"
  UPDATE_CI_DEVELOP_SCRIPT: "${{ env.SCRIPTS_PATH }}/update-ci-develop.sh"

jobs:
  update-ci-develop:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: write  # Required to push changes to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update ci/develop branch
        run: ${UPDATE_CI_DEVELOP_SCRIPT}
